name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏞️</text></svg>

      - name: Generate Contributors Images
        id: contributors
        # uses: jaywcjlove/github-action-contributors@main
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: renovate\[bot\]
          output: build/CONTRIBUTORS.svg
          avatarSize: 36

      - name: Generate Contributors Images
        id: contributor_name
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          hideName: 'true'
          avatarSize: 100

      - name: Generate Contributors Images
        id: contributor_table
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          avatarSize: 100

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: README.md
          openDelimiter: '<!--GAMFC-->'
          closeDelimiter: '<!--GAMFC-END-->'
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          openDelimiter: '<!--GAMFC_TABEL_HIDE_NAME-->'
          closeDelimiter: '<!--GAMFC_TABEL_HIDE_NAME-END-->'
          body: |
            ${{steps.contributor_name.outputs.htmlTable}}

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          openDelimiter: '<!--GAMFC_TABEL-->'
          closeDelimiter: '<!--GAMFC_TABEL-END-->'
          body: |
            ${{steps.contributor_table.outputs.htmlTable}}

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          openDelimiter: '<!--GAMFC_TABEL_BOTS-->'
          closeDelimiter: '<!--GAMFC_TABEL_BOTS-END-->'
          body: |
            ${{steps.contributor_table.outputs.htmlTableBots}}

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          openDelimiter: '<!--GAMFC_TABEL_COLLABORATORS-->'
          closeDelimiter: '<!--GAMFC_TABEL_COLLABORATORS-END-->'
          body: |
            ${{steps.contributor_table.outputs.htmlCollaboratorsTable}}

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_dir: ./build

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (小弟调调™|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/github-action-contributors/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 
            
            ${{ steps.changelog.outputs.changelog }}

            ```yml
            - run: mkdir -p build
            - name: Generate Contributors Images
              uses: jaywcjlove/github-action-contributors@main
              with:
                token: xxxxxxx
                filter-author: renovate\[bot\]
                output: build/CONTRIBUTORS.svg

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: xxxxxxx
                publish_dir: ./build
            ```

            <a href="https://github.com/jaywcjlove/github-action-contributors/graphs/contributors">
              <img src="https://jaywcjlove.github.io/github-action-contributors/CONTRIBUTORS.svg" />
            </a>
